---
language: python
python: "2.7"

env:
  - ANSIBLE_VERSION="2.4,<2.5"
  - ANSIBLE_VERSION="2.5,<2.6"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt

install:
  - pip install "ansible>=$ANSIBLE_VERSION"
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  - ./tests/run.sh
