---
language: python
python: "2.7"

env:
  - ANSIBLE_VERSION="1.8,<1.9"
  - ANSIBLE_VERSION="1.9,<2.0"
  - ANSIBLE_VERSION="2.0,<2.1"
  - ANSIBLE_VERSION="2.1,<2.2"
  - ANSIBLE_VERSION="2.2,<2.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt

install:
  - pip install "ansible>=$ANSIBLE_VERSION"
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  - ./tests/run.sh
