---

- import_tasks: install.yml
  tags:
    - rsnapshot
    - rsnapshot_install

- name: add healthcheck to crontab execution
  include: monitoring.yml
  loop_control:
    loop_var: cron
  with_items: "{{ rsnapshot_crontab }}"
  when: healthchecks_api_key is defined
  tags:
  - rsnapshot
  - rsnapshot_config

- import_tasks: config.yml
  tags:
    - rsnapshot
    - rsnapshot_config

- include_tasks: not-root.yml
  when: rsnapshot_master_host_user != 'root' and rsnapshot_master_host_user_uses_sudo
  tags:
    - rsnapshot
    - rsnapshot_config
