---

- name: Sudo configuration for the backup system user
  template:
    src: sudo_backupuser
    dest: "/etc/sudoers.d/{{ rsnapshot_master_host_user }}"
    owner: root
    group: root
    mode: 0440
  when: ansible_os_family == "Debian" and ansible_lsb.major_release|int >= 6

- name: Install the 'rsync-wrapper.sh' script, for rights elevation for localhost backup
  copy:
    src: rsync-wrapper.sh
    dest: /usr/local/bin/rsync-wrapper.sh
    owner: root
    group: root
    mode: 0755
